[package]
name = "elf-lang"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
peg = "0.8.5"
simple_logger = { version = "5.1.0", default-features = false, features = ["colored", "colors"] }
