[package]
name = "santac"
version = "0.1.1"
description = "Compiler/interpreter for the SantASM language"
edition = "2024"

[dependencies]
santa-lang = { path = "../santa-lang" }
clap = { version = "4.5.52", features = ["derive"] }
log = "0.4.28"
